# These are supported funding model platforms

github: [involvex]
custom:
  [
    "https://buymeacoffee.com/involvex",
    "https://paypal.me/involvex",
    "https://rewards.bing.com/welcome?rh=14525F68&ref=rafsrchae&form=ML2XE3&OCID=ML2XE3&PUBL=RewardsDO&CREA=ML2XE3",
  ]
